version: 0.2

env:
  variables:
    ECR_SUFFIX: .dkr.ecr.us-east-1.amazonaws.com
    PROJECT_NAME: carbon-app

phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text | cut -f1)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - ECR_IMAGE_URI=$AWS_ACCOUNT_ID$ECR_SUFFIX/$PROJECT_NAME
  build:
    commands:
      - echo Build started on `date`
      - docker buildx build --platform linux/amd64 -t $ECR_IMAGE_URI:$CODEBUILD_BUILD_NUMBER .
      - docker push $ECR_IMAGE_URI:$CODEBUILD_BUILD_NUMBER
      - docker tag $ECR_IMAGE_URI:$CODEBUILD_BUILD_NUMBER $ECR_IMAGE_URI:latest
      - docker push $ECR_IMAGE_URI:latest

artifacts:
  files:
    - "**/*"
